Add capsule exec guide
nervosnetwork/docs-new pull request #150
Opened 2023-01-18 07:17 UTC by mohanson

2023-01-18 07:36 UTC, sopium commented
We should probably release a new version of ckb-std and capsule and add an example using the new entrypoint and argv api.

2023-01-18 09:44 UTC, linnnsss commented on website/docs/labs/capsule-exec.md
> +[Exec](https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0034-vm-syscalls-2/0034-vm-syscalls-2.md#exec) is a new syscall provided by [ckb2021](https://github.com/nervosnetwork/rfcs/blob/master/r
[Exec](https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0034-vm-syscalls-2/0034-vm-syscalls-2.md#exec) is a new syscall provided by [ckb2021](https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0037-ckb2021/0037-ckb2021.md). To understand what exec syscall does, we recommend reading [this article] (https://man7.org/linux/man-pages/man3/exec.3.html) first. In short: Exec runs an executable file from specified cell data in the context of an already existing VM, replacing the previous executable. The used cycles do not change, but the code, registers, and memory of the VM are replaced by those of the new program, meaning **control flow will never return to the main script**.

2023-01-18 09:44 UTC, linnnsss commented on website/docs/labs/capsule-exec.md
> +Compare with [Dynamic libraries](https://docs.nervos.org/docs/labs/capsule-dynamic-loading-tutorial/), exec has the following significant advantages:
Compared with

2023-01-18 09:44 UTC, linnnsss commented on website/docs/labs/capsule-exec.md
> +## Write Always failure sub-script
Write `always-failure` sub-script

2023-01-18 09:44 UTC, linnnsss commented on website/docs/labs/capsule-exec.md
> +Put the following codes into `contracts/always-failure/main.rs`. As you can see, the script always returns 42, which means that if the script is used as a lock script, the cell will never be unlocked
the following code

2023-01-18 09:44 UTC, linnnsss commented on website/docs/labs/capsule-exec.md
> +Put the following codes into `contracts/ckb-exec-demo/main.rs`.
the following code

2023-01-18 09:44 UTC, linnnsss commented on website/docs/labs/capsule-exec.md
> +This script does only one thing, when executing `exec(0, Source::CellDep, 0, 0, &[])`, CKB-VM will look for the first dep_cell, and execute the code in it.
... does only one thing: When

2023-01-19 01:09 UTC, XuJiandong requested changes

2023-01-19 01:09 UTC, XuJiandong commented on website/docs/labs/capsule-exec.md
> +
also add disadvantages: 1. never return 2. hard to exchanged data between scripts

2023-01-30 03:46 UTC, phroi commented
Just noticed this super interesting docs pull request, this phrase in particular caught my eye:
> All sub-scripts are complete scripts. They can be used alone, or they can be called by exec.

For example does this entail I can directly call Exec Omnilock from my scripts?
If so, how should the arguments be formatted? Could you make a Rust example on how to call Omnilock with Exec?

2023-01-31 04:18 UTC, mohanson commented
> Just noticed this super interesting docs pull request, this phrase in particular caught my eye:
> 
> > All sub-scripts are complete scripts. They can be used alone, or they can be called by exec.
> 
> For example does this entail I can directly call Exec Omnilock from my scripts? If so, how should the arguments be formatted? Could you make a Rust example on how to call Omnilock with Exec?

I updated this draft to show how to pass in and use parameters.

Please read the latest draft and demo: https://github.com/mohanson/ckb-exec-demo

2023-01-31 18:50 UTC, phroi commented
Much better, thanks!! I still had some doubts about the `place` argument, but after looking up [the `Exec` implementation](https://github.com/nervosnetwork/ckb/blob/develop/script/src/syscalls/exec.rs) I got it.

So to reply to my own question: I don't believe it's possible to use `OmniLock` with `Exec` unless the implementation is changed to account for this new use.

2023-02-02 04:19 UTC, merged